export const StripeSupportedCountries = [
  {
    value: "US",
    display_name: "🇺🇸 United States",
    currency: "USD",
    capabilities: ["card_payments", "crypto_payments", "transfers"],
  },
  {
    value: "CA",
    display_name: "🇨🇦 Canada",
    currency: "CAD",
    capabilities: ["card_payments", "crypto_payments", "transfers"],
  },
  {
    value: "GB",
    display_name: "🇬🇧 United Kingdom",
    currency: "GBP",
    capabilities: ["card_payments", "crypto_payments", "transfers"],
  },
  {
    value: "AU",
    display_name: "🇦🇺 Australia",
    currency: "AUD",
    capabilities: ["card_payments", "crypto_payments", "transfers"],
  },
  {
    value: "NZ",
    display_name: "🇳🇿 New Zealand",
    currency: "NZD",
    capabilities: ["card_payments", "crypto_payments", "transfers"],
  },

  {
    value: "SG",
    display_name: "🇸🇬 Singapore",
    currency: "SGD",
    capabilities: ["card_payments", "crypto_payments", "transfers"],
  },
  {
    value: "HK",
    display_name: "🇭🇰 Hong Kong",
    currency: "HKD",
    capabilities: ["card_payments", "crypto_payments", "transfers"],
  },
  {
    value: "JP",
    display_name: "🇯🇵 Japan",
    currency: "JPY",
    capabilities: ["card_payments", "crypto_payments", "transfers"],
  },

  {
    value: "AT",
    display_name: "🇦🇹 Austria",
    currency: "EUR",
    capabilities: ["card_payments", "transfers"],
  },
  {
    value: "BE",
    display_name: "🇧🇪 Belgium",
    currency: "EUR",
    capabilities: ["card_payments", "transfers"],
  },
  {
    value: "BG",
    display_name: "🇧🇬 Bulgaria",
    currency: "BGN",
    capabilities: ["card_payments", "transfers"],
  },
  {
    value: "HR",
    display_name: "🇭🇷 Croatia",
    currency: "EUR",
    capabilities: ["card_payments", "transfers"],
  },
  {
    value: "CY",
    display_name: "🇨🇾 Cyprus",
    currency: "EUR",
    capabilities: ["card_payments", "transfers"],
  },
  {
    value: "CZ",
    display_name: "🇨🇿 Czech Republic",
    currency: "CZK",
    capabilities: ["card_payments", "transfers"],
  },
  {
    value: "DK",
    display_name: "🇩🇰 Denmark",
    currency: "DKK",
    capabilities: ["card_payments", "transfers"],
  },
  {
    value: "EE",
    display_name: "🇪🇪 Estonia",
    currency: "EUR",
    capabilities: ["card_payments", "transfers"],
  },
  {
    value: "FI",
    display_name: "🇫🇮 Finland",
    currency: "EUR",
    capabilities: ["card_payments", "transfers"],
  },
  {
    value: "FR",
    display_name: "🇫🇷 France",
    currency: "EUR",
    capabilities: ["card_payments", "transfers"],
  },
  {
    value: "DE",
    display_name: "🇩🇪 Germany",
    currency: "EUR",
    capabilities: ["card_payments", "transfers"],
  },
  {
    value: "GR",
    display_name: "🇬🇷 Greece",
    currency: "EUR",
    capabilities: ["card_payments", "transfers"],
  },
  {
    value: "HU",
    display_name: "🇭🇺 Hungary",
    currency: "HUF",
    capabilities: ["card_payments", "transfers"],
  },
  {
    value: "IE",
    display_name: "🇮🇪 Ireland",
    currency: "EUR",
    capabilities: ["card_payments", "transfers"],
  },
  {
    value: "IT",
    display_name: "🇮🇹 Italy",
    currency: "EUR",
    capabilities: ["card_payments", "transfers"],
  },
  {
    value: "LV",
    display_name: "🇱🇻 Latvia",
    currency: "EUR",
    capabilities: ["card_payments", "transfers"],
  },
  {
    value: "LT",
    display_name: "🇱🇹 Lithuania",
    currency: "EUR",
    capabilities: ["card_payments", "transfers"],
  },
  {
    value: "LU",
    display_name: "🇱🇺 Luxembourg",
    currency: "EUR",
    capabilities: ["card_payments", "transfers"],
  },
  {
    value: "MT",
    display_name: "🇲🇹 Malta",
    currency: "EUR",
    capabilities: ["card_payments", "transfers"],
  },
  {
    value: "NL",
    display_name: "🇳🇱 Netherlands",
    currency: "EUR",
    capabilities: ["card_payments", "transfers"],
  },
  {
    value: "NO",
    display_name: "🇳🇴 Norway",
    currency: "NOK",
    capabilities: ["card_payments", "transfers"],
  },
  {
    value: "PL",
    display_name: "🇵🇱 Poland",
    currency: "PLN",
    capabilities: ["card_payments", "transfers"],
  },
  {
    value: "PT",
    display_name: "🇵🇹 Portugal",
    currency: "EUR",
    capabilities: ["card_payments", "transfers"],
  },
  {
    value: "RO",
    display_name: "🇷🇴 Romania",
    currency: "RON",
    capabilities: ["card_payments", "transfers"],
  },
  {
    value: "SK",
    display_name: "🇸🇰 Slovakia",
    currency: "EUR",
    capabilities: ["card_payments", "transfers"],
  },
  {
    value: "SI",
    display_name: "🇸🇮 Slovenia",
    currency: "EUR",
    capabilities: ["card_payments", "transfers"],
  },
  {
    value: "ES",
    display_name: "🇪🇸 Spain",
    currency: "EUR",
    capabilities: ["card_payments", "transfers"],
  },
  {
    value: "SE",
    display_name: "🇸🇪 Sweden",
    currency: "SEK",
    capabilities: ["card_payments", "transfers"],
  },
  {
    value: "CH",
    display_name: "🇨🇭 Switzerland",
    currency: "CHF",
    capabilities: ["card_payments", "transfers"],
  },

  {
    value: "BR",
    display_name: "🇧🇷 Brazil",
    currency: "BRL",
    capabilities: ["card_payments", "transfers"],
  },
  {
    value: "MX",
    display_name: "🇲🇽 Mexico",
    currency: "MXN",
    capabilities: ["card_payments", "transfers"],
  },
];
